DESCRIPTION = "Qualcomm Technologies, Inc. WLAN CLD low latency driver version 3.0 for Hasting Prime"

inherit qcacld-30-common

WLAN_MODULE_NAME = "wlan-hsp"

PACKAGES =+ "kernel-module-${WLAN_MODULE_NAME}"

DEPENDS += "virtual/kernel wlan-cnss-core"

EXTRA_OEMAKE += "CONFIG_QCA_CLD_WLAN_PROFILE=qca6490 CHIP_NAME=qca6490 MODNAME=${WLAN_MODULE_NAME}"
EXTRA_OEMAKE += "CONFIG_CNSS2=y CONFIG_CNSS_QCA6490=y CONFIG_HIF_PCI=y"
EXTRA_OEMAKE += "CONFIG_WLAN_DISABLE_EXPORT_SYMBOL=y CONFIG_SLUB_DEBUG_ON=n CONFIG_SLUB_DEBUG=n"
EXTRA_OEMAKE += "CONFIG_FEATURE_COEX=y CONFIG_QCACLD_FEATURE_BTC_CHAIN_MODE=y"
EXTRA_OEMAKE += "CONFIG_CONNECTION_ROAMING_CFG=n"
EXTRA_OEMAKE += "CONFIG_WLAN_ENABLE_GPIO_WAKEUP=y"
EXTRA_OEMAKE += "CONFIG_DP_MULTIPASS_SUPPORT=n CONFIG_WLAN_DP_FEATURE_DEFERRED_REO_QDESC_DESTROY=n"
EXTRA_OEMAKE += "CONFIG_AUTO_PLATFORM=y"
EXTRA_OEMAKE += "KBUILD_EXTRA=KBUILD_EXTRA_SYMBOLS=${STAGING_INCDIR}/wlan-cnss-core/Module.symvers"
