DESCRIPTION = "wifi drivers qcacld-3.2 for genoa chip"

inherit qcacld

DEPENDS += "wlan-cnss-core"


EXTRA_OEMAKE += "CONFIG_WLAN_DISABLE_EXPORT_SYMBOL=y"

EXTRA_OEMAKE += "CONFIG_QCA_CLD_WLAN_PROFILE=genoa.pci.debug" 


SINGLE_CHIP_NAME = "qcn7605"
WLAN_MODULE_NAME = "wlan-genoa-pcie"

EXTRA_OEMAKE += "CONFIG_CNSS2=y"
EXTRA_OEMAKE += "WLAN_CFG_OVERRIDE="CONFIG_IPA_DISABLE_OVERRIDE=y CONFIG_QCN7605_PCIE_GOLBAL_RESET_SUPPORT=y CONFIG_GET_DRIVER_MODE=y CONFIG_WLAN_MAX_VDEVS=4 CONFIG_QCACLD_FEATURE_BTC_CHAIN_MODE=y CONFIG_FEATURE_COEX=y CONFIG_QCACLD_FEATURE_COEX_CONFIG=y CONFIG_FW_THERMAL_THROTTLE=y""
EXTRA_OEMAKE += "${@oe.utils.conditional('FEATURE_SINGLE_MSI', '1', 'CONFIG_ONE_MSI_VECTOR=y', '', d)}"
#EXTRA_OEMAKE += "CONFIG_ONE_MSI_VECTOR=y"
#EXTRA_OEMAKE += "WLAN_CFG_OVERRIDE="CONFIG_IPA_DISABLE_OVERRIDE=y CONFIG_GET_DRIVER_MODE=y CONFIG_WLAN_MAX_VDEVS=4 CONFIG_QCACLD_FEATURE_BTC_CHAIN_MODE=y CONFIG_FEATURE_COEX=y CONFIG_QCACLD_FEATURE_COEX_CONFIG=y  CONFIG_FW_THERMAL_THROTTLE=y""
EXTRA_OEMAKE += "MODNAME=${WLAN_MODULE_NAME}"
EXTRA_OEMAKE += "DYNAMIC_SINGLE_CHIP=${SINGLE_CHIP_NAME}"

