DESCRIPTION = "Qualcomm Technologies, Inc. WLAN CLD low latency driver version 3.0 for Hasting Prime"

inherit qcacld-30-common

WLAN_MODULE_NAME = "wlan-hamilton"

PACKAGES =+ "kernel-module-${WLAN_MODULE_NAME}"

DEPENDS += "virtual/kernel wlan-cnss-core"

EXTRA_OEMAKE += "CONFIG_QCA_CLD_WLAN_PROFILE=kiwi_v2 CHIP_NAME=kiwi MODNAME=${WLAN_MODULE_NAME}"
EXTRA_OEMAKE += "CONFIG_CNSS2=y CONFIG_CNSS_KIWI=y"
EXTRA_OEMAKE += "CONFIG_WLAN_DISABLE_EXPORT_SYMBOL=y CONFIG_SLUB_DEBUG_ON=n CONFIG_SLUB_DEBUG=n"
EXTRA_OEMAKE += "CONFIG_LINUX_QCMBR=y DEVELOPER_DISABLE_BUILD_TIMESTAMP=y"
EXTRA_OEMAKE += "CONFIG_RX_FISA=n CONFIG_WLAN_FEATURE_11BE_MLO=y CONFIG_QCOM_TDLS=n CONFIG_BAND_6GHZ=y CONFIG_DP_MULTIPASS_SUPPORT=n"
EXTRA_OEMAKE += "CONFIG_CNSS2_SSR_DRIVER_DUMP=y"
EXTRA_OEMAKE += "CONFIG_NON_QC_PLATFORM=y CONFIG_DUMP_LOG_BUF_CNT=128"
EXTRA_OEMAKE += "WLAN_CTRL_NAME=wlan CONFIG_QCACLD_FEATURE_APF=y"

#EXTRA_OEMAKE += "CONFIG_FEATURE_COEX=y CONFIG_QCACLD_FEATURE_BTC_CHAIN_MODE=y"
#EXTRA_OEMAKE += "CONFIG_CONNECTION_ROAMING_CFG=n"
#EXTRA_OEMAKE += "CONFIG_WLAN_ENABLE_GPIO_WAKEUP=y"
EXTRA_OEMAKE += "KBUILD_EXTRA=KBUILD_EXTRA_SYMBOLS=${STAGING_INCDIR}/wlan-cnss-core/Module.symvers"
