DESCRIPTION = "Qualcomm Technologies, Inc. WLAN CLD high latency driver version 3.2 for Dual Rome"

inherit qcacld-30-common

WLAN_MODULE_NAME = "qca6174-cnss2"
WLAN_CHIP_NAME   = "cnss2"

PACKAGES =+ "kernel-module-${WLAN_MODULE_NAME}"

EXTRA_OEMAKE += "CONFIG_QCA_CLD_WLAN_PROFILE=qca6174 CONFIG_ROME_IF=pci"
EXTRA_OEMAKE += "CONFIG_WLAN_DISABLE_EXPORT_SYMBOL=y CONFIG_IPA_OFFLOAD=n"
EXTRA_OEMAKE += "MODNAME=${WLAN_MODULE_NAME} CHIP_NAME=${WLAN_CHIP_NAME}"
