DESCRIPTION = "Qualcomm Technologies, Inc. WLAN CLD low latency driver version 3.0 for Hasting"

inherit qcacld-30-common

WLAN_MODULE_NAME = "wlan-hasting"

PACKAGES =+ "kernel-module-${WLAN_MODULE_NAME}"

DEPENDS += "wlan-cnss-core"

EXTRA_OEMAKE += "CONFIG_QCA_CLD_WLAN_PROFILE=qca6390 CHIP_NAME=qca6390 MODNAME=${WLAN_MODULE_NAME}"
EXTRA_OEMAKE += "CONFIG_CNSS2=y CONFIG_CNSS_QCA6390=y CONFIG_HIF_PCI=y"
EXTRA_OEMAKE += "CONFIG_WLAN_DISABLE_EXPORT_SYMBOL=y CONFIG_SLUB_DEBUG_ON=n CONFIG_SLUB_DEBUG=n"
EXTRA_OEMAKE += "CONFIG_BUS_AUTO_SUSPEND=n CONFIG_RX_DEFRAG_DO_NOT_REINJECT=y"
EXTRA_OEMAKE += "KBUILD_EXTRA=KBUILD_EXTRA_SYMBOLS=${STAGING_INCDIR}/wlan-cnss-core/Module.symvers"
