DESCRIPTION = "Qualcomm Technologies, Inc. WLAN CLD low latency driver version 3.2 for Genoa"

inherit qcacld-30-common

WLAN_MODULE_NAME = "wlan-genoa-pcie"

PACKAGES =+ "kernel-module-${WLAN_MODULE_NAME}"

DEPENDS += "virtual/kernel wlan-cnss-core"

EXTRA_OEMAKE += "CONFIG_QCA_CLD_WLAN_PROFILE=genoa.pci.debug CHIP_NAME=qcn7605 MODNAME=${WLAN_MODULE_NAME}"
EXTRA_OEMAKE += "CONFIG_CNSS2=y"
EXTRA_OEMAKE += "CONFIG_WLAN_DISABLE_EXPORT_SYMBOL=y CONFIG_SLUB_DEBUG_ON=n CONFIG_SLUB_DEBUG=n"
EXTRA_OEMAKE += "CONFIG_LINUX_QCMBR=y DEVELOPER_DISABLE_BUILD_TIMESTAMP=y"

EXTRA_OEMAKE += " WLAN_CFG_OVERRIDE="CONFIG_IPA_DISABLE_OVERRIDE=y CONFIG_QCN7605_PCIE_GOLBAL_RESET_SUPPORT=y CONFIG_GET_DRIVER_MODE=y CONFIG_WLAN_MAX_VDEVS=4 CONFIG_QCACLD_FEATURE_BTC_CHAIN_MODE=y CONFIG_FEATURE_COEX=y CONFIG_QCACLD_FEATURE_COEX_CONFIG=y CONFIG_FW_THERMAL_THROTTLE=y""
EXTRA_OEMAKE += "KBUILD_EXTRA=KBUILD_EXTRA_SYMBOLS=${STAGING_INCDIR}/wlan-cnss-core/Module.symvers"

