SCMVERSION = "n"

FILESEXTRAPATHS_prepend := "${THISDIR}/files:"

SRC_URI += "file://lk-4.9/0001-porting_cfg_patch_for_LK49.patch \
            file://lk-4.9/0002-porting_mhi_header_for_LK49.patch \
	    file://lk-4.9/0003-cfg80211-Add-flags-to-support-WPA3-STA-AP-function.patch \
          "



do_copy_defconfig_append () {

cat >> ${WORKDIR}/defconfig <<KERNEL_EXTRACONFIGS
CONFIG_BCMDHD=n
CONFIG_BCMDHD_1363=n
CONFIG_CFG80211_INTERNAL_REGDB=y
CONFIG_CLD_LL_CORE=n
CONFIG_ATH10K=n
CONFIG_ATH10K_PCI=n
CONFIG_ARCH_ALPINE=n
CONFIG_ARCH_HISI=n
CONFIG_ARCH_MVEBU=n
CONFIG_ARCH_QCOM=n
CONFIG_ARM_SMMU=y
CONFIG_STACKTRACE=y
CONFIG_BRIDGE=y
CONFIG_TMPFS=y
CONFIG_CNSS_LOGGER=n
CONFIG_CRC_CCITT=y
CONFIG_TYPEC_TCPM=n
KERNEL_EXTRACONFIGS

}
