BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILES += "${@bb.utils.contains('KERNELVERSION', '4.9', '${LAYERDIR}/recipes-libs/firmware-imx_7.5.bbappend ', '', d)} "
BBFILES += "${@bb.utils.contains('KERNELVERSION', '4.9', '${LAYERDIR}/recipes-libs/alsa-lib_1.1.4.1.bbappend ', '', d)} "
BBFILE_COLLECTIONS += "qti-connectivity"
BBFILE_PATTERN_qti-connectivity := "^${LAYERDIR}"
BBFILE_PRIORITY_qti-connectivity = "12"
