#BBMASK for third party BSP platform.
BBMASK_append = "|meta-qti-connectivity/recipes-products/images/automotive-connx-image.bb"
BBMASK_append = "|meta-qti-connectivity/recipes-kernel/linux-kernel/linux-msm-4.4_git.bbappend"
BBMASK_append = "|meta-qti-connectivity/recipes-kernel/lk/lk_git.bbappend"
BBMASK_append = "|meta-qti-connectivity/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend"
BBMASK_append = "|meta-qti-connectivity/recipes-connectivity/wlan-driver/qcacld-ll_3.0.bb"
BBMASK_append = "|meta-qti-connectivity/recipes-connectivity/wlan-driver/qcacld-ll-dualwifi_3.0.bb"

